version: "2"

services:
  bbsparse:
    image: zinking/bbsparse:1.2
    extra_hosts:
      zzy: 10.162.73.141
    ports:
      - "8001:8001"
    volumes:
          - /data/:/data
    entrypoint: /data/bbsparse/volume/entry_point.sh

  mining-ionic:
    image: zinking/mining-ionic:1.0
    extra_hosts:
          zzy: 10.162.73.141
    ports:
      - "8002:8002"
    volumes:
          - /data/:/data

  mining-play:
    image: zinking/mining-play:1.2
    extra_hosts:
          zzy: 10.162.73.141
    ports:
      - "9000:9000"
    volumes:
      - /data/:/data

