version: "2"

services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/dbdump:./docker-entrypoint-initdb.d

  web:
    image: zinking/mining:v1.0
    ports:
      - "9000:9000"
    depends_on:
      - "db"
    volumes:
      - ./data/:/data


./data
./data/dbdump
./data/dbdump/mining.2016-09-25.sql
./data/config.sh
./data/mining.2016-09-25.sql.tar.gz
./docker-compose.yml
./Dockerfile
